18-Jan-23 20:06:01 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
18-Jan-23 20:06:01 - [33mPress CTRL+C to quit[0m
18-Jan-23 20:06:43 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
18-Jan-23 20:06:43 - [33mPress CTRL+C to quit[0m
18-Jan-23 20:32:25 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
18-Jan-23 20:32:25 - [33mPress CTRL+C to quit[0m
18-Jan-23 20:32:44 - Connection to mongo success
18-Jan-23 20:32:44 - 127.0.0.1 - - [18/Jan/2023 20:32:44] "GET / HTTP/1.1" 200 -
18-Jan-23 20:32:47 - Connection to mongo success
18-Jan-23 20:32:47 - 127.0.0.1 - - [18/Jan/2023 20:32:47] "GET / HTTP/1.1" 200 -
18-Jan-23 20:32:55 - Connection to mongo success
18-Jan-23 20:32:55 - Starting new HTTPS connection (1): api.telegram.org:443
18-Jan-23 20:32:56 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
18-Jan-23 20:32:56 - 127.0.0.1 - - [18/Jan/2023 20:32:56] "POST / HTTP/1.1" 200 -
18-Jan-23 20:32:59 - Connection to mongo success
18-Jan-23 20:32:59 - Starting new HTTPS connection (1): api.telegram.org:443
18-Jan-23 20:32:59 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendDocument HTTP/1.1" 400 107
18-Jan-23 20:32:59 - 127.0.0.1 - - [18/Jan/2023 20:32:59] "POST / HTTP/1.1" 200 -
19-Jan-23 00:23:22 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 00:23:22 - [33mPress CTRL+C to quit[0m
19-Jan-23 00:23:27 - Connection to mongo success
19-Jan-23 00:23:27 - 127.0.0.1 - - [19/Jan/2023 00:23:27] "GET / HTTP/1.1" 200 -
19-Jan-23 00:23:27 - Connection to mongo success
19-Jan-23 00:23:27 - 127.0.0.1 - - [19/Jan/2023 00:23:27] "[33mGET /apple-touch-icon-precomposed.png HTTP/1.1[0m" 404 -
19-Jan-23 00:23:27 - Connection to mongo success
19-Jan-23 00:23:27 - 127.0.0.1 - - [19/Jan/2023 00:23:27] "[33mGET /apple-touch-icon.png HTTP/1.1[0m" 404 -
19-Jan-23 00:23:31 - Connection to mongo success
19-Jan-23 00:23:31 - 127.0.0.1 - - [19/Jan/2023 00:23:31] "GET / HTTP/1.1" 200 -
19-Jan-23 00:46:53 - Connection to mongo success
19-Jan-23 00:46:54 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 00:46:54 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 00:46:54 - 127.0.0.1 - - [19/Jan/2023 00:46:54] "POST / HTTP/1.1" 200 -
19-Jan-23 00:46:57 - Connection to mongo success
19-Jan-23 00:46:57 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 00:46:58 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 258
19-Jan-23 00:46:58 - 127.0.0.1 - - [19/Jan/2023 00:46:58] "POST / HTTP/1.1" 200 -
19-Jan-23 00:46:59 - Connection to mongo success
19-Jan-23 00:46:59 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 00:47:00 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendDocument HTTP/1.1" 400 107
19-Jan-23 00:47:00 - 127.0.0.1 - - [19/Jan/2023 00:47:00] "POST / HTTP/1.1" 200 -
19-Jan-23 00:52:51 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 00:52:51 - [33mPress CTRL+C to quit[0m
19-Jan-23 00:53:01 - Connection to mongo success
19-Jan-23 00:53:01 - 127.0.0.1 - - [19/Jan/2023 00:53:01] "GET / HTTP/1.1" 200 -
19-Jan-23 00:53:04 - Connection to mongo success
19-Jan-23 00:53:04 - 127.0.0.1 - - [19/Jan/2023 00:53:04] "GET / HTTP/1.1" 200 -
19-Jan-23 00:53:09 - Connection to mongo success
19-Jan-23 00:53:09 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 00:53:09 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 00:53:09 - 127.0.0.1 - - [19/Jan/2023 00:53:09] "POST / HTTP/1.1" 200 -
19-Jan-23 00:53:12 - Connection to mongo success
19-Jan-23 00:53:12 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 00:53:13 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendDocument HTTP/1.1" 400 109
19-Jan-23 00:53:13 - 127.0.0.1 - - [19/Jan/2023 00:53:13] "POST / HTTP/1.1" 200 -
19-Jan-23 01:02:58 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 01:02:58 - [33mPress CTRL+C to quit[0m
19-Jan-23 01:03:04 - Connection to mongo success
19-Jan-23 01:03:04 - 127.0.0.1 - - [19/Jan/2023 01:03:04] "GET / HTTP/1.1" 200 -
19-Jan-23 01:03:07 - Connection to mongo success
19-Jan-23 01:03:07 - 127.0.0.1 - - [19/Jan/2023 01:03:07] "GET / HTTP/1.1" 200 -
19-Jan-23 01:03:12 - Connection to mongo success
19-Jan-23 01:03:12 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:03:12 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:03:12 - 127.0.0.1 - - [19/Jan/2023 01:03:12] "POST / HTTP/1.1" 200 -
19-Jan-23 01:03:15 - Connection to mongo success
19-Jan-23 01:03:15 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:03:15 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 258
19-Jan-23 01:03:15 - 127.0.0.1 - - [19/Jan/2023 01:03:15] "POST / HTTP/1.1" 200 -
19-Jan-23 01:03:17 - Connection to mongo success
19-Jan-23 01:03:17 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:17 - 127.0.0.1 - - [19/Jan/2023 01:03:17] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:03:18 - Connection to mongo success
19-Jan-23 01:03:18 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:18 - 127.0.0.1 - - [19/Jan/2023 01:03:18] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:03:20 - Connection to mongo success
19-Jan-23 01:03:20 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:20 - 127.0.0.1 - - [19/Jan/2023 01:03:20] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:03:25 - Connection to mongo success
19-Jan-23 01:03:25 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:25 - 127.0.0.1 - - [19/Jan/2023 01:03:25] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:03:33 - Connection to mongo success
19-Jan-23 01:03:33 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:33 - 127.0.0.1 - - [19/Jan/2023 01:03:33] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:03:49 - Connection to mongo success
19-Jan-23 01:03:49 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:03:49 - 127.0.0.1 - - [19/Jan/2023 01:03:49] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:04:03 - Connection to mongo success
19-Jan-23 01:04:03 - 127.0.0.1 - - [19/Jan/2023 01:04:03] "GET / HTTP/1.1" 200 -
19-Jan-23 01:04:07 - Connection to mongo success
19-Jan-23 01:04:07 - 127.0.0.1 - - [19/Jan/2023 01:04:07] "GET / HTTP/1.1" 200 -
19-Jan-23 01:04:22 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 01:04:22 - [33mPress CTRL+C to quit[0m
19-Jan-23 01:04:27 - Connection to mongo success
19-Jan-23 01:04:27 - 127.0.0.1 - - [19/Jan/2023 01:04:27] "GET / HTTP/1.1" 200 -
19-Jan-23 01:04:29 - Connection to mongo success
19-Jan-23 01:04:29 - 127.0.0.1 - - [19/Jan/2023 01:04:29] "GET / HTTP/1.1" 200 -
19-Jan-23 01:05:26 - Connection to mongo success
19-Jan-23 01:05:26 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:05:26 - 127.0.0.1 - - [19/Jan/2023 01:05:26] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:06:29 - Connection to mongo success
19-Jan-23 01:06:29 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:06:29 - 127.0.0.1 - - [19/Jan/2023 01:06:29] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:08:07 - Connection to mongo success
19-Jan-23 01:08:07 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:08:07 - 127.0.0.1 - - [19/Jan/2023 01:08:07] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:09:30 - Connection to mongo success
19-Jan-23 01:09:30 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:09:30 - 127.0.0.1 - - [19/Jan/2023 01:09:30] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:10:35 - Connection to mongo success
19-Jan-23 01:10:35 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:10:35 - 127.0.0.1 - - [19/Jan/2023 01:10:35] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:11:38 - Connection to mongo success
19-Jan-23 01:11:38 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:11:38 - 127.0.0.1 - - [19/Jan/2023 01:11:38] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:12:42 - Connection to mongo success
19-Jan-23 01:12:42 - Exception on / [POST]
Traceback (most recent call last):
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 70, in index
    tel_send_document(chat_id)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/app.py", line 55, in tel_send_document
    k = requests.post(url, json=payload)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/nuraim/Desktop/my_projects/zeon/flask_bot/venv/lib/python3.10/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type BufferedReader is not JSON serializable
19-Jan-23 01:12:42 - 127.0.0.1 - - [19/Jan/2023 01:12:42] "[35m[1mPOST / HTTP/1.1[0m" 500 -
19-Jan-23 01:13:50 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 01:13:50 - [33mPress CTRL+C to quit[0m
19-Jan-23 01:13:55 - Connection to mongo success
19-Jan-23 01:13:55 - 127.0.0.1 - - [19/Jan/2023 01:13:55] "GET / HTTP/1.1" 200 -
19-Jan-23 01:13:57 - Connection to mongo success
19-Jan-23 01:13:57 - 127.0.0.1 - - [19/Jan/2023 01:13:57] "GET / HTTP/1.1" 200 -
19-Jan-23 01:14:00 - Connection to mongo success
19-Jan-23 01:14:00 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:00 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendDocument HTTP/1.1" 400 109
19-Jan-23 01:14:00 - 127.0.0.1 - - [19/Jan/2023 01:14:00] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:00 - Connection to mongo success
19-Jan-23 01:14:00 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:01 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:14:01 - 127.0.0.1 - - [19/Jan/2023 01:14:01] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:01 - Connection to mongo success
19-Jan-23 01:14:01 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:02 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:14:02 - 127.0.0.1 - - [19/Jan/2023 01:14:02] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:02 - Connection to mongo success
19-Jan-23 01:14:02 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:02 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:14:02 - 127.0.0.1 - - [19/Jan/2023 01:14:02] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:03 - Connection to mongo success
19-Jan-23 01:14:03 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:03 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 258
19-Jan-23 01:14:03 - 127.0.0.1 - - [19/Jan/2023 01:14:03] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:03 - Connection to mongo success
19-Jan-23 01:14:03 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:04 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:14:04 - 127.0.0.1 - - [19/Jan/2023 01:14:04] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:07 - Connection to mongo success
19-Jan-23 01:14:07 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:08 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 01:14:08 - 127.0.0.1 - - [19/Jan/2023 01:14:08] "POST / HTTP/1.1" 200 -
19-Jan-23 01:14:11 - Connection to mongo success
19-Jan-23 01:14:11 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 01:14:11 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendDocument HTTP/1.1" 400 109
19-Jan-23 01:14:11 - 127.0.0.1 - - [19/Jan/2023 01:14:11] "POST / HTTP/1.1" 200 -
19-Jan-23 10:54:41 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
19-Jan-23 10:54:41 - [33mPress CTRL+C to quit[0m
19-Jan-23 10:54:45 - Connection to mongo success
19-Jan-23 10:54:45 - 127.0.0.1 - - [19/Jan/2023 10:54:45] "GET / HTTP/1.1" 200 -
19-Jan-23 10:54:48 - Connection to mongo success
19-Jan-23 10:54:48 - 127.0.0.1 - - [19/Jan/2023 10:54:48] "GET / HTTP/1.1" 200 -
19-Jan-23 10:54:53 - Connection to mongo success
19-Jan-23 10:54:53 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 10:54:54 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 10:54:54 - 127.0.0.1 - - [19/Jan/2023 10:54:54] "POST / HTTP/1.1" 200 -
19-Jan-23 10:54:57 - Connection to mongo success
19-Jan-23 10:54:57 - Starting new HTTPS connection (1): api.telegram.org:443
19-Jan-23 10:54:57 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 265
19-Jan-23 10:54:57 - 127.0.0.1 - - [19/Jan/2023 10:54:57] "POST / HTTP/1.1" 200 -
20-Jan-23 12:03:51 - Connection to mongo success
20-Jan-23 12:03:51 - Starting new HTTPS connection (1): api.telegram.org:443
20-Jan-23 12:03:51 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 285
20-Jan-23 12:03:51 - 127.0.0.1 - - [20/Jan/2023 12:03:51] "POST / HTTP/1.1" 200 -
20-Jan-23 12:11:19 - Connection to mongo success
20-Jan-23 12:11:19 - Starting new HTTPS connection (1): api.telegram.org:443
20-Jan-23 12:11:19 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 285
20-Jan-23 12:11:19 - 127.0.0.1 - - [20/Jan/2023 12:11:19] "POST / HTTP/1.1" 200 -
20-Jan-23 12:11:24 - Connection to mongo success
20-Jan-23 12:11:24 - Starting new HTTPS connection (1): api.telegram.org:443
20-Jan-23 12:11:24 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 278
20-Jan-23 12:11:24 - 127.0.0.1 - - [20/Jan/2023 12:11:24] "POST / HTTP/1.1" 200 -
20-Jan-23 12:11:31 - Connection to mongo success
20-Jan-23 12:11:31 - Starting new HTTPS connection (1): api.telegram.org:443
20-Jan-23 12:11:32 - https://api.telegram.org:443 "POST /bot5827147957:AAGiPsgwfI7wdbvXNoYY-r4QSWtBB74ZFVc/sendMessage HTTP/1.1" 200 285
20-Jan-23 12:11:32 - 127.0.0.1 - - [20/Jan/2023 12:11:32] "POST / HTTP/1.1" 200 -
20-Jan-23 18:26:21 - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
20-Jan-23 18:26:21 - [33mPress CTRL+C to quit[0m
20-Jan-23 18:26:28 - Connection to mongo success
20-Jan-23 18:26:28 - 127.0.0.1 - - [20/Jan/2023 18:26:28] "GET / HTTP/1.1" 200 -
20-Jan-23 18:26:29 - Connection to mongo success
20-Jan-23 18:26:29 - 127.0.0.1 - - [20/Jan/2023 18:26:29] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
20-Jan-23 18:27:06 - Connection to mongo success
20-Jan-23 18:27:06 - 127.0.0.1 - - [20/Jan/2023 18:27:06] "GET / HTTP/1.1" 200 -
20-Jan-23 18:27:07 - Connection to mongo success
20-Jan-23 18:27:07 - 127.0.0.1 - - [20/Jan/2023 18:27:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
